-- SELEZIONARE TUTTI GLI STUDENTI NATI NEL 1990

SELECT * FROM `students` WHERE `date_of_birth` LIKE '1990-%'

-- SELEZIONARE TUTTI I CORSI CHE VALGONO PIù DI 10 CREDITI

SELECT * FROM `courses` WHERE `cfu` >= 10