-- SELEZIONARE TUTTI GLI STUDENTI NATI NEL 1990

SELECT * FROM `students` WHERE `date_of_birth` LIKE '1990-%'

-- SELEZIONARE TUTTI I CORSI CHE VALGONO PIù DI 10 CREDITI

SELECT * FROM `courses` WHERE `cfu` >= 10

-- SELEZIONARE TUTTI GLI STUDENTI CHE HANNO PIù DI 30 ANNI

SELECT * FROM `students` WHERE 2022 - YEAR(`date_of_birth`) >= 30

-- SELEZIONARE TUTTI I CORSI DEL PRIMO SEMESTRE DEL PRIMO ANNO DI UN QUALSIASI CORSO DI LAUREA

SELECT * FROM `courses` WHERE `period` = 'I semestre' AND `year` = 1

-- SELEZIONARE TUTTI GLI APPUNTAMENTI D'ESAME CHE AVVENGONO NEL POMERIGGIO DOPO LE 14 DEL 20/06/2020

SELECT * FROM `exams` WHERE `hour` > '14:00:00' AND `date` = '2020-06-20'

-- SELEZIONARE TUTTI I CORSI DI LAUREA MAGISTRALE

SELECT * FROM `degrees` WHERE `level` = 'magistrale'

-- DA QUANTI DIPARTIMENTI è COMPOSTA L'UNIVERSITà?

SELECT COUNT(*) FROM `departments`

-- QUANTI SONO GLI INSEGNANTI CHE NON HANNO UN NUMERO DI TELEFONO?

SELECT COUNT(*) FROM `teachers` WHERE `phone` = NULL